###Общая линейная регрессионная модель

In [ ]:
import numpy as np

In [ ]:
X = np.array((41, 50, 81, 104, 120, 139, 154, 180, 208, 241, 250, 269, 301))
Y = np.array((4, 8, 10, 14, 16, 20, 19, 23, 26, 30, 31, 36, 37))

$y_i = β_0 + β_1⋅x_i + ε_i$

In [ ]:
n = len(X)
m = 2 # amount of β_i

$F =
 \begin{pmatrix}
  1 & X_1 \\
  1 & X_2 \\
  \vdots  & \vdots \\
  1 & X_n
 \end{pmatrix}$

In [ ]:
FT_F = np.array(([len(X), sum(X)], [sum(X), sum(X ** 2)]))
FT_F

array([[    13,   2138],
       [  2138, 438202]])

In [ ]:
FT_F_inv = np.linalg.inv(FT_F)
FT_F_inv

array([[ 3.89311485e-01, -1.89946179e-03],
       [-1.89946179e-03,  1.15495806e-05]])

In [ ]:
FT_Y = np.array((sum(Y), sum(X * Y)))
FT_Y

array([  274, 55805])

$\hat {\overline{β}} = (F^T⋅F)^{-1}⋅F^T⋅Y$

In [ ]:
β = FT_F_inv @ FT_Y
β

array([0.67188175, 0.12407181])

$\hat{\delta}^2=\frac{1}{n - m}\ \sum_{i=0}^{n-1} (y_i - \hatβ_0 - \hatβ_1⋅x_i)^2$

In [ ]:
δ2 = 1 / (n - m) * sum((Y - β[0] - β[1] * X) ** 2)
δ2

1.4615316585310791

$Σ_{\hat {\overline{β}}}=(F^T⋅F)^{-1}⋅\hat{\delta}^2$

$Σ_{\hat {\overline{β}}}=
 \begin{pmatrix}
  D{\hat{\beta}_0} & cov(\hat{\beta}_0, \hat{\beta}_1)\\
  cov(\hat{\beta}_0, \hat{\beta}_1) & D{\hat{\beta}_1}
 \end{pmatrix}$

In [ ]:
Σ = FT_F_inv * δ2
Σ

array([[ 5.68991060e-01, -2.77612354e-03],
       [-2.77612354e-03,  1.68800776e-05]])